#nullable enable

namespace Smartstore.Core.AI
{
    /// <summary>
    /// Represents the response of an AI chat completion.
    /// </summary>
    public record AIChatCompletionResponse(string? Message, int? Index = null)
    {
        /// <summary>
        /// Gets the message generated by the AI chat completion.
        /// </summary>
        public string? Message { get; init; } = Message;

        /// <summary>
        /// Gets the index of the AI chat completion response.
        /// </summary>
        public int? Index { get; init; } = Index;
    }
}
