#nullable enable

namespace Smartstore.Core.AI
{
    /// <summary>
    /// Represents the response of an AI chat completion.
    /// </summary>
    public record AIChatCompletionResponse(string? Content, int? Index = null, string? FinishReason = null)
    {
        /// <summary>
        /// Gets the response content generated by the AI chat completion.
        /// </summary>
        public string? Content { get; init; } = Content;

        /// <summary>
        /// Gets the index of the AI chat completion response.
        /// </summary>
        public int? Index { get; init; } = Index;

        /// <summary>
        /// "stop" if the AI response has been fully transmitted.
        /// "length" if the token limit is reached and the AI's response is incomplete (chunked).
        /// <c>null</c> by default.
        /// </summary>
        public string? FinishReason { get; init; } = FinishReason;
    }
}
