<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Smartstore.Packager</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Smartstore\Smartstore.csproj" />
        <ProjectReference Include="..\..\src\Smartstore.Core\Smartstore.Core.csproj" />
    </ItemGroup>

</Project>
