using System.Data;
using FluentMigrator;
using Smartstore.Blog.Domain;
using Smartstore.Core.Content.Media;
using Smartstore.Core.Data.Migrations;
using Smartstore.Core.Identity;
using Smartstore.Core.Localization;
using Smartstore.Domain;

namespace Smartstore.Blog.Migrations
{
    [MigrationVersion("2021-09-14 13:30:00", "Blog: Initial")]
    internal class Initial : Migration
    {
        public override void Up()
        {
            const string blogPost = "BlogPost";
            const string blogComment = "BlogComment";
            
            const string id = nameof(BaseEntity.Id);

            if (!Schema.Table(blogPost).Exists())
            {
                Create.Table(blogPost)
                    .WithColumn(id).AsInt32().PrimaryKey().Identity().NotNullable()
                    // TODO: (mh) (core) EF model and FluentMigration must ALWAYS be in sync!! You can't just add an index here
                    // and omit it in the domain entity ([Index] attribute). Background: On app installation the data schema for any module is obtained from the current
                    // EF model snapshot. But on post-app installation (standalone module installation) the schema is generated by executing migration classes
                    // (because it is too late for EF model composition at this stage).
                    .WithColumn(nameof(BlogPost.Title)).AsString(450).NotNullable()
                        .Indexed("IX_Title")
                    .WithColumn(nameof(BlogPost.Body)).AsString(int.MaxValue).Nullable()
                    .WithColumn(nameof(BlogPost.AllowComments)).AsBoolean().NotNullable()
                    .WithColumn(nameof(BlogPost.ApprovedCommentCount)).AsInt32().NotNullable()
                    .WithColumn(nameof(BlogPost.NotApprovedCommentCount)).AsInt32().NotNullable()
                    .WithColumn(nameof(BlogPost.Tags)).AsString(4000).Nullable()
                    .WithColumn(nameof(BlogPost.StartDateUtc)).AsDateTime2().Nullable()
                    .WithColumn(nameof(BlogPost.EndDateUtc)).AsDateTime2().Nullable()
                    .WithColumn(nameof(BlogPost.MetaKeywords)).AsString(400).Nullable()
                    .WithColumn(nameof(BlogPost.MetaDescription)).AsString(4000).Nullable()
                    .WithColumn(nameof(BlogPost.MetaTitle)).AsString(400).Nullable()
                    .WithColumn(nameof(BlogPost.LimitedToStores)).AsBoolean().NotNullable()
                    .WithColumn(nameof(BlogPost.CreatedOnUtc)).AsDateTime2().Nullable()
                    .WithColumn(nameof(BlogPost.SectionBg)).AsString(100).Nullable()
                    .WithColumn(nameof(BlogPost.Intro)).AsString(int.MaxValue).Nullable()
                    .WithColumn(nameof(BlogPost.DisplayTagsInPreview)).AsBoolean().NotNullable()
                    .WithColumn(nameof(BlogPost.IsPublished)).AsBoolean().NotNullable()
                    .WithColumn(nameof(BlogPost.PreviewDisplayType)).AsInt32().NotNullable()
                    .WithColumn(nameof(BlogPost.MediaFileId)).AsInt32().Nullable()
                        .Indexed("IX_MediaFileId")
                        .ForeignKey(nameof(MediaFile), id).OnDelete(Rule.None)
                    .WithColumn(nameof(BlogPost.PreviewMediaFileId)).AsInt32().Nullable()
                        .Indexed("IX_PreviewMediaFileId")
                        .ForeignKey(nameof(MediaFile), id).OnDelete(Rule.None)
                    .WithColumn(nameof(BlogPost.LanguageId)).AsInt32().NotNullable()
                        .Indexed("IX_LanguageId")
                        .ForeignKey(nameof(Language), id).OnDelete(Rule.None);
            }

            if (!Schema.Table(blogComment).Exists())
            {
                Create.Table(blogComment)
                    .WithColumn(id).AsInt32().PrimaryKey().Identity().NotNullable()
                    .WithColumn(nameof(BlogComment.CommentText)).AsString(int.MaxValue).Nullable()
                    .WithColumn(nameof(BlogComment.BlogPostId)).AsInt32().NotNullable()
                        .ForeignKey(blogPost, id).OnDelete(Rule.Cascade);

                Create.ForeignKey()
                    .FromTable(blogComment).ForeignColumn(id)
                    .ToTable(nameof(CustomerContent)).PrimaryColumn(id);
            }
        }

        public override void Down()
        {
            // INFO: no down initial migration. Leave blog schema as it is or ask merchant to delete it.
        }
    }
}
