using Microsoft.AspNetCore.Mvc.ApiExplorer;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace Smartstore.Web.Api.Swagger;

/// <summary>
/// Generated by ChatGPT. Sets "Example Value" by writing MediaType.Example (paths/.../content/.../example), while schema examples remain empty.
/// Without this filter the schema examples would display too much unformatted JSON, which makes it confusing, impractical or unusable for humans.
/// </summary>
internal sealed class SwaggerExamplesOperationFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        if (operation == null || context == null)
            return;

        // Request body: best-effort CLR type
        var requestType = TryGetRequestBodyType(context.ApiDescription);
        if (operation.RequestBody?.Content != null)
        {
            foreach (var kv in operation.RequestBody.Content)
            {
                if (IsJsonMediaType(kv.Key))
                    TrySetExample(kv.Value, context, requestType);
            }
        }

        // Responses: per status code best-effort CLR type
        if (operation.Responses == null)
            return;

        foreach (var kvResp in operation.Responses)
        {
            var statusCode = ParseStatusCode(kvResp.Key);
            var responseType = TryGetResponseType(context.ApiDescription, statusCode);

            var resp = kvResp.Value;
            if (resp?.Content == null)
                continue;

            foreach (var kv in resp.Content)
            {
                if (IsJsonMediaType(kv.Key))
                    TrySetExample(kv.Value, context, responseType);
            }
        }
    }

    private static bool IsJsonMediaType(string mediaType)
    {
        if (string.IsNullOrWhiteSpace(mediaType))
            return false;

        return mediaType.IndexOf("json", StringComparison.OrdinalIgnoreCase) >= 0;
    }

    private static void TrySetExample(OpenApiMediaType mediaType, OperationFilterContext context, Type clrTypeHint)
    {
        if (mediaType == null || mediaType.Schema == null)
            return;

        // Keep explicit examples
        if (mediaType.Example != null)
            return;

        var hint = NormalizeHintType(clrTypeHint) ?? typeof(object);
        mediaType.Example = SwaggerExamplesSchemaFilter.BuildExample(mediaType.Schema, context.SchemaRepository, hint);
    }

    private static int ParseStatusCode(string key)
    {
        if (string.IsNullOrWhiteSpace(key))
            return 0;

        if (string.Equals(key, "default", StringComparison.OrdinalIgnoreCase))
            return 0;

        if (int.TryParse(key, out var n))
            return n;

        return 0;
    }

    private static Type TryGetRequestBodyType(ApiDescription api)
    {
        if (api?.ParameterDescriptions == null)
            return null;

        var p = api.ParameterDescriptions.FirstOrDefault(x => x.Source != null && x.Source.CanAcceptDataFrom(Microsoft.AspNetCore.Mvc.ModelBinding.BindingSource.Body));
        return p?.Type;
    }

    private static Type TryGetResponseType(ApiDescription api, int statusCode)
    {
        if (api?.SupportedResponseTypes == null || api.SupportedResponseTypes.Count == 0)
            return null;

        // Prefer exact match
        if (statusCode != 0)
        {
            var exact = api.SupportedResponseTypes.FirstOrDefault(r => r.StatusCode == statusCode);
            if (exact?.Type != null)
                return exact.Type;
        }

        // Fall back to first "successful" response
        var success = api.SupportedResponseTypes.FirstOrDefault(r => r.StatusCode >= 200 && r.StatusCode <= 299 && r.Type != null);
        if (success?.Type != null)
            return success.Type;

        // Otherwise: first with a type
        return api.SupportedResponseTypes.FirstOrDefault(r => r.Type != null)?.Type;
    }

    private static Type NormalizeHintType(Type t)
    {
        if (t == null)
            return null;

        // unwrap Task<T>
        if (typeof(Task).IsAssignableFrom(t) && t.IsGenericType)
            t = t.GetGenericArguments()[0];

        // unwrap ActionResult<T>
        if (t.IsGenericType && t.GetGenericTypeDefinition() == typeof(ActionResult<>))
            t = t.GetGenericArguments()[0];

        // unwrap OData SingleResult<T> (prevents weird reflection hits)
        if (t.IsGenericType && t.GetGenericTypeDefinition().FullName == "Microsoft.AspNetCore.OData.Results.SingleResult`1")
            t = t.GetGenericArguments()[0];

        return t;
    }
}
